### ISSUE TITLE
Typo spotted in the BalanceSheet contract

### ISSUE THREAD

**Issue by clemlak** [hifi-finance/hifi-protocol#25]
The notice of the `BalanceSheet.sol` contract has a typo line 18:

>  * @notice Manages the debt vault for all fyToens.

Should be

>  * @notice Manages the debt vault for all fyTokens.

**Comment by paulrberg** [comment]
Fixed in [215ad2a](https://github.com/hifi-finance/hifi-protocol/commit/215ad2ad6896ac05173adb4eee0a29a3727a7a4c).
