### ISSUE TITLE
2nd typo spotted in the BalanceSheet contract

### ISSUE THREAD

**Issue by clemlak** [hifi-finance/hifi-protocol#26]
In the `BalanceSheet.sol` contract, [line 365](https://github.com/MainframeHQ/mainframe-lending-protocol/blob/main/contracts/BalanceSheet.sol#L365), the comment  of the `depositCollateral` function says:

> * @param collateralAmount The amount of collateral to withdraw.

It should be:

> * @param collateralAmount The amount of collateral to deposit.

**Comment by paulrberg** [comment]
Fixed in [215ad2a](https://github.com/hifi-finance/hifi-protocol/commit/215ad2ad6896ac05173adb4eee0a29a3727a7a4c).
