### ISSUE TITLE
Rounding errors in "supplyUnderlyingAndRepayBorrow"

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/hifi-protocol#27]
As explained by @defi-david on Slack:

> Let's assume the user owes `12.875914707132095215` fyTokens.  When we attempt to pay off the entire debt by calling  `supplyUnderlyingAndRepayBorrow`, we'll pass in `12.875914` as the underlying amount.  Unfortunately, this will result in the user having a dusty debt of `0.000000707132095215`.
>
> Passing `12.875915` instead causes an expected error.
>
> Could you modify the `supplyUnderlyingAndRepayBorrow` to accept an `underlyingAmount` larger than the fyToken debt, but somehow safeguard us from making too big a mistake here, such has passing in much larger `underlyingAmount` than desired.  I figure if we pass an extra `0.000001` as the `underlyingAmount` and we mint a bit extra fyToken dust, we can just let that sit in the user's dsProxy after repayment.

This is about the [supplyUnderlyingAndRepayBorrow](https://github.com/hifi-finance/hifi-protocol/blob/f2446aea90e640e85a78e467b37fc5ca3543d6c8/contracts/proxy/BatterseaTargetV1.sol#L402-L415) function part of the `BatterseaTargetV1` contract.

**Comment by scorpion9979** [comment]
I think we'll need to create a `supplyUnderlyingAndRepayAllBorrow` method for this, which translates to burning all of the user's debt. For the UI, we could distinguish which method gets called by using the default method (`supplyUnderlyingAndRepayBorrow`) when an amount is entered manually, and using `supplyUnderlyingAndRepayAllBorrow` when "max" button is clicked.

**Comment by paulrberg** [comment]
I'm closing this issue because of two reasons:

1. We will stop using Balancer in the next release.
2. The DSProxy target will get overhauled as part of my multi-collateral work.
