### ISSUE TITLE
Get rid of "ERR_" prefix in require revert reasons

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/hifi-protocol#32]
This would save gas.

**Comment by clemlak** [comment]
Yes! I totally agree, the prefix `ERR_` is useless here since we already know an error occurred.

**Comment by clemlak** [comment]
Done in: https://github.com/hifi-finance/hifi-protocol/pull/34

**Comment by paulrberg** [comment]
#36 has been merged.
