### ISSUE TITLE
Improve the inheritance architecture of the contracts by using overriding public variables

### ISSUE THREAD

**Issue by clemlak** [hifi-finance/hifi-protocol#33]
While studying Uniswap v3, I've recently discovered that public variables can override a constant function defined in an interface. For example, the function `token0()` defined [here](https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/interfaces/pool/IUniswapV3PoolImmutables.sol#L13) in the `IUniswapV3PoolImmutables.sol` interface is then overridden by the public variable `token0` defined [here](https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/UniswapV3Pool.sol#L44) in the child contract UniswapV3Pool.

This means that our current inheritance architecture could be improved by changing our current flow from:
```
Storage (abstract contract) -> Interface (abstract contract) -> Logic (contract)
```
to:
```
Interface (interface) -> Storage (abstract contract) -> Logic (contract)
```

Additionally, all the `struct` and `enum` types will have to be defined directly into the interface.

I think this change would make the architecture simpler and more logic.

**Comment by paulrberg** [comment]
Done via #36.
