### ISSUE TITLE
Implement Solidity v0.8.4 custom errors

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/hifi-protocol#44]
See this [tweet](https://twitter.com/PaulRBerg/status/1387471133528760328).

**Comment by scorpion9979** [comment]
Let's agree about the implementation details. Here for example, where should the error be defined? I'm thinking we either define it at the contract file itself or have a single `Errors.sol` file where all errors are defined. Also, I suggest same error name but converted from the capitalized snake case string format to Pascal Case (e.g., `CLUTCH_COLLATERAL_NOT_AUTHORIZED -> ClutchCollateralNotAuthorized`).
![image](https://user-images.githubusercontent.com/4002635/119983912-778d1b00-bfc9-11eb-97e4-b558b38831d9.png)

**Comment by scorpion9979** [comment]
Putting this on hold for now, as Solhint and Hardhat still haven't supported Solidity ver. 0.8.4.

**Comment by paulrberg** [comment]
Solhint has, but Hardhat hasn't, yes.

https://github.com/protofire/solhint/issues/289

**Comment by paulrberg** [comment]
I agree with your suggestions to create an `Errors.sol` file and switch to using PascalCase.

**Comment by paulrberg** [comment]
I'm removing the "stale" tag now, because [Hardhat v2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) added support for Solidity v0.8.4 custom errors.

**Comment by scorpion9979** [comment]
We should replace all `pragma solidity >=0.8.0;` occurrences with `pragma solidity >=0.8.5;` when we implement this.

**Comment by paulrberg** [comment]
`pragma solidity >=0.8.4`*, but yes.

**Comment by paulrberg** [comment]
Done via [1ab2786](https://github.com/hifi-finance/hifi-protocol/commit/1ab27868b83429c0425c4743958473e115e9dc06).
