### ISSUE TITLE
Delete Erc20Mintable and use GodModeErc20

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/hifi-protocol#45]
See [GodModeErc20.sol](https://github.com/paulrberg/contracts/blob/ad564e46ace325bfdf0955e379d8b03ef0d67e27/contracts/token/erc20/GodModeErc20.sol).

**Comment by scorpion9979** [comment]
This issue is dependent on https://github.com/paulrberg/contracts/issues/7, and thus should also be marked as stale.

**Comment by paulrberg** [comment]
Done in [749dc90](https://github.com/hifi-finance/hifi-protocol/commit/749dc903232163436345441c6c4050f14f94f149).
